### ISSUE TITLE
It looks like this is in Entity Framework (...finally 🎉)

### ISSUE THREAD

**Issue by NathanLBCooper** [mivano/EFIndexInclude#2]
Taking `params string[] propertyNames`. Since 2.2 as `ForSqlServerHasIndex().ForSqlServerInclude()` and since 3.0 as `HasIndex().ForSqlServerInclude()`

eg
```
modelBuilder.Entity<MyEntity>()
.HasIndex(r => new { r.Foo, r.Status, r.Bar})
.ForSqlServerInclude(nameof(MyEntity.Fizz)) 
```

Thank you for your workaround in the meantime. This remains great guide to putting custom stuff into the migrations in a way that can be regenerated. But it looks like people coming across this repository in 2019 should just be directed to use whats already in Entity Framework.

https://github.com/aspnet/EntityFrameworkCore/commit/a3dd2a0b94947de0f3145ce5ead7ed43b92aad0a#diff-be76f0abc80a471803a2f6f48b375ad2

**Comment by mivano** [comment]
That is great news, thanks for bringing it up!

**Comment by NathanLBCooper** [comment]
7722c4d83ff98c72a1724d15601d4d1ae5650bdf
